<template>
  <ContainerCard title="Upcoming Appointments">
    <FullAppointmentsTable :appointments="appointments" />
  </ContainerCard>
</template>

<script>
import ContainerCard from "@/components/UI/ContainerCard.vue";
import FullAppointmentsTable from "@/components/Tables/FullAppointmentsTable.vue";

export default {
  components: {
    ContainerCard,
    FullAppointmentsTable,
  },
  data() {
    return {
      appointments: [
        {
          id: 1,
          doctor: "Dr. John Doe",
          patient: "Alice Johnson",
          date: "2025-04-01",
          time: "10:00 AM",
          status: "Scheduled",
          room: "101",
        },
        {
          id: 2,
          doctor: "Dr. Emily White",
          patient: "Bob Matthews",
          date: "2025-04-03",
          time: "2:00 PM",
          status: "Scheduled",
          room: "202",
        },
        {
          id: 3,
          doctor: "Dr. Michael Brown",
          patient: "Sarah Turner",
          date: "2025-04-05",
          time: "11:00 AM",
          status: "Finished",
          room: "305",
        },
        {
          id: 4,
          doctor: "Dr. Sarah Johnson",
          patient: "David Moore",
          date: "2025-04-06",
          time: "9:00 AM",
          status: "Scheduled",
          room: "107",
        },
        {
          id: 5,
          doctor: "Dr. Robert Adams",
          patient: "Linda Green",
          date: "2025-04-07",
          time: "1:30 PM",
          status: "Scheduled",
          room: "203",
        },
        {
          id: 6,
          doctor: "Dr. William Harris",
          patient: "James Carter",
          date: "2025-04-08",
          time: "3:00 PM",
          status: "Finished",
          room: "404",
        },
        {
          id: 7,
          doctor: "Dr. John Doe",
          patient: "Daniel Brown",
          date: "2025-04-10",
          time: "10:30 AM",
          status: "Scheduled",
          room: "105",
        },
        {
          id: 8,
          doctor: "Dr. Jessica Green",
          patient: "Emily White",
          date: "2025-04-11",
          time: "11:45 AM",
          status: "Scheduled",
          room: "301",
        },
        {
          id: 9,
          doctor: "Dr. David Lee",
          patient: "Michael Smith",
          date: "2025-04-12",
          time: "9:15 AM",
          status: "Finished",
          room: "506",
        },
        {
          id: 10,
          doctor: "Dr. Jane Smith",
          patient: "Olivia Davis",
          date: "2025-04-13",
          time: "2:30 PM",
          status: "Scheduled",
          room: "208",
        },
        {
          id: 11,
          doctor: "Dr. Robert Adams",
          patient: "Sophia Taylor",
          date: "2025-04-14",
          time: "10:00 AM",
          status: "Scheduled",
          room: "109",
        },
        {
          id: 12,
          doctor: "Dr. Emily White",
          patient: "Mason Clark",
          date: "2025-04-16",
          time: "4:00 PM",
          status: "Finished",
          room: "310",
        },
        {
          id: 13,
          doctor: "Dr. Sarah Johnson",
          patient: "Isabella Wilson",
          date: "2025-04-18",
          time: "1:00 PM",
          status: "Scheduled",
          room: "112",
        },
        {
          id: 14,
          doctor: "Dr. Michael Brown",
          patient: "Jackson Lee",
          date: "2025-04-19",
          time: "10:00 AM",
          status: "Scheduled",
          room: "403",
        },
        {
          id: 15,
          doctor: "Dr. William Harris",
          patient: "Henry Harris",
          date: "2025-04-20",
          time: "2:15 PM",
          status: "Scheduled",
          room: "306",
        },
        {
          id: 16,
          doctor: "Dr. Jessica Green",
          patient: "Charlotte Anderson",
          date: "2025-04-21",
          time: "3:45 PM",
          status: "Finished",
          room: "501",
        },
        {
          id: 17,
          doctor: "Dr. David Lee",
          patient: "Lucas Hall",
          date: "2025-04-22",
          time: "9:30 AM",
          status: "Scheduled",
          room: "504",
        },
        {
          id: 18,
          doctor: "Dr. Jane Smith",
          patient: "Amelia Young",
          date: "2025-04-24",
          time: "2:00 PM",
          status: "Finished",
          room: "105",
        },
        {
          id: 19,
          doctor: "Dr. Sarah Johnson",
          patient: "Elijah Martinez",
          date: "2025-04-26",
          time: "11:00 AM",
          status: "Scheduled",
          room: "109",
        },
        {
          id: 20,
          doctor: "Dr. Robert Adams",
          patient: "Benjamin Robinson",
          date: "2025-04-27",
          time: "1:00 PM",
          status: "Scheduled",
          room: "202",
        },
      ],
    };
  },
};
</script>
