<template>
  <ContainerCard title="Upcoming Appointments">
    <FullAppointmentsTable :appointments="appointments" />
  </ContainerCard>
</template>

<script>
import ContainerCard from "@/components/UI/ContainerCard.vue";
import FullAppointmentsTable from "@/components/Tables/FullAppointmentsTable.vue";

export default {
  components: {
    ContainerCard,
    FullAppointmentsTable,
  },
  data() {
    return {
      appointments: [
        {
          doctor: "Dr. John Doe",
          patient: "Alice Johnson",
          date: "2025-04-01",
          time: "10:00 AM",
          status: "Scheduled",
          room: "101",
        },
        {
          doctor: "Dr. Emily White",
          patient: "Bob Matthews",
          date: "2025-04-03",
          time: "2:00 PM",
          status: "Scheduled",
          room: "202",
        },
        {
          doctor: "Dr. Michael Brown",
          patient: "Sarah Turner",
          date: "2025-04-05",
          time: "11:00 AM",
          status: "Finished",
          room: "305",
        },
        {
          doctor: "Dr. Sarah Johnson",
          patient: "David Moore",
          date: "2025-04-06",
          time: "9:00 AM",
          status: "Scheduled",
          room: "107",
        },
        {
          doctor: "Dr. Robert Adams",
          patient: "Linda Green",
          date: "2025-04-07",
          time: "1:30 PM",
          status: "Scheduled",
          room: "203",
        },
        {
          doctor: "Dr. William Harris",
          patient: "James Carter",
          date: "2025-04-08",
          time: "3:00 PM",
          status: "Finished",
          room: "404",
        },
        {
          doctor: "Dr. John Doe",
          patient: "Daniel Brown",
          date: "2025-04-10",
          time: "10:30 AM",
          status: "Scheduled",
          room: "105",
        },
        {
          doctor: "Dr. Jessica Green",
          patient: "Emily White",
          date: "2025-04-11",
          time: "11:45 AM",
          status: "Scheduled",
          room: "301",
        },
        {
          doctor: "Dr. David Lee",
          patient: "Michael Smith",
          date: "2025-04-12",
          time: "9:15 AM",
          status: "Finished",
          room: "506",
        },
        {
          doctor: "Dr. Jane Smith",
          patient: "Olivia Davis",
          date: "2025-04-13",
          time: "2:30 PM",
          status: "Scheduled",
          room: "208",
        },
        {
          doctor: "Dr. Robert Adams",
          patient: "Sophia Taylor",
          date: "2025-04-14",
          time: "10:00 AM",
          status: "Scheduled",
          room: "109",
        },
        {
          doctor: "Dr. Emily White",
          patient: "Mason Clark",
          date: "2025-04-16",
          time: "4:00 PM",
          status: "Finished",
          room: "310",
        },
        {
          doctor: "Dr. Sarah Johnson",
          patient: "Isabella Wilson",
          date: "2025-04-18",
          time: "1:00 PM",
          status: "Scheduled",
          room: "112",
        },
        {
          doctor: "Dr. Michael Brown",
          patient: "Jackson Lee",
          date: "2025-04-19",
          time: "10:00 AM",
          status: "Scheduled",
          room: "403",
        },
        {
          doctor: "Dr. William Harris",
          patient: "Henry Harris",
          date: "2025-04-20",
          time: "2:15 PM",
          status: "Scheduled",
          room: "306",
        },
        {
          doctor: "Dr. Jessica Green",
          patient: "Charlotte Anderson",
          date: "2025-04-21",
          time: "3:45 PM",
          status: "Finished",
          room: "501",
        },
        {
          doctor: "Dr. David Lee",
          patient: "Lucas Hall",
          date: "2025-04-22",
          time: "9:30 AM",
          status: "Scheduled",
          room: "504",
        },
        {
          doctor: "Dr. Jane Smith",
          patient: "Amelia Young",
          date: "2025-04-24",
          time: "2:00 PM",
          status: "Finished",
          room: "105",
        },
        {
          doctor: "Dr. Sarah Johnson",
          patient: "Elijah Martinez",
          date: "2025-04-26",
          time: "11:00 AM",
          status: "Scheduled",
          room: "109",
        },
        {
          doctor: "Dr. Robert Adams",
          patient: "Benjamin Robinson",
          date: "2025-04-27",
          time: "1:00 PM",
          status: "Scheduled",
          room: "202",
        },
        {
          doctor: "Dr. Michael Brown",
          patient: "Amos Moore",
          date: "2025-04-28",
          time: "10:30 AM",
          status: "Finished",
          room: "107",
        },
        {
          doctor: "Dr. William Harris",
          patient: "Zoey Allen",
          date: "2025-04-29",
          time: "4:00 PM",
          status: "Scheduled",
          room: "401",
        },
        {
          doctor: "Dr. Jessica Green",
          patient: "Leo Scott",
          date: "2025-05-01",
          time: "9:00 AM",
          status: "Scheduled",
          room: "202",
        },
        {
          doctor: "Dr. David Lee",
          patient: "Grace Perez",
          date: "2025-05-03",
          time: "10:00 AM",
          status: "Scheduled",
          room: "305",
        },
        {
          doctor: "Dr. Sarah Johnson",
          patient: "Oliver King",
          date: "2025-05-05",
          time: "11:30 AM",
          status: "Finished",
          room: "209",
        },
        {
          doctor: "Dr. Michael Brown",
          patient: "Amelia Turner",
          date: "2025-05-06",
          time: "2:30 PM",
          status: "Scheduled",
          room: "501",
        },
        {
          doctor: "Dr. Robert Adams",
          patient: "Ethan Adams",
          date: "2025-05-08",
          time: "3:00 PM",
          status: "Scheduled",
          room: "308",
        },
        {
          doctor: "Dr. Emily White",
          patient: "Jack Evans",
          date: "2025-05-09",
          time: "9:30 AM",
          status: "Finished",
          room: "103",
        },
        {
          doctor: "Dr. John Doe",
          patient: "Harper Taylor",
          date: "2025-05-10",
          time: "12:00 PM",
          status: "Scheduled",
          room: "104",
        },
        {
          doctor: "Dr. Sarah Johnson",
          patient: "Mia Lee",
          date: "2025-05-11",
          time: "1:45 PM",
          status: "Scheduled",
          room: "204",
        },
        {
          doctor: "Dr. Jessica Green",
          patient: "Samuel Thompson",
          date: "2025-05-12",
          time: "4:00 PM",
          status: "Finished",
          room: "305",
        },
        {
          doctor: "Dr. William Harris",
          patient: "Sophie Jackson",
          date: "2025-05-14",
          time: "10:30 AM",
          status: "Scheduled",
          room: "205",
        },
      ],
    };
  },
};
</script>

<style scoped>
/* Styles for the page can go here if needed */
</style>
